name: CI/CD Deployment to GKE
on:
    push:
        branches:
            - main

env:
    PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
    GKE_CLUSTER: "my-cluser" #Extracted from GCP Kuberneetes engine(one with green tick)
    GKE_REGION: your-gke-cluster-zone #Copy the region from clusters
    DEPLOYMENT_NAME: "mlops-app"
    REPOSITORY: " " #Copied from my repo in GCP Container Registry

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        container:
            image: google/cloud-sdk:latest
            options: --entrypoint /bin/bash

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Authenticate to GCP
              uses: google-github-actions/auth@v1
              with:
                credentials_json: ${{secrets.GCP_SA_KEY}}

            - name: Configure GCloud
              run: |
                gcloud config set project $PROJECT_ID
                gcloud auth configure-docker "zone name-docker.pkg.dev"

            - name: Build and Push Docker Image
              run: |
                docker build -t $IMAGE:$GITHUB_SHA .
                docker push $IMAGE:$GITHUB_SHA
            
            - name: GKE Configuration
              run: |
                gcloud cntainer clusters get-credentials $GKE_CLUSTER --region $GKE_REGION --project $PROJECT_ID

            - name: Deloying to Kuberenetes
              run: |
                kubesectl apply -f venv/kubernetes-deployment.yaml
                kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$IMAGE:$GITHUB_SHA    
                
        #Connects the updated code to updated image


